import 'package:flutter/material.dart';

class AppStrings {
  static const bool isDemo = false;
  static const List<Locale> supportedLocales = [Locale('en'), Locale('ar')];
  static const Locale defaultLocale = Locale('en');
  static const List<Map<String, String>> languages = [
    {"id": "en", "name": "English"},
    {"id": "ar", "name": "عربي"},
  ];
  static const String defaultCurrency = "USD";
  static const int defaultBudgetDurationDays = 30;
  static const ThemeMode defaultThemeMode = ThemeMode.system;
  static const bool enableScreenshot = false;
  static const bool enableLockApp = false;
  static const int paginationLimit = 20;

  static const String defaultColorPicked = "1ca0d9";
  static const List<String> knownColors = [
    defaultColorPicked,
    "1e90ff",
    "16a085",
    "e67e22",
    "9b59b6",
    "34495e",
    "2ed573",
    "2ecc71",
    "2980b9",
    "6c5ce7",
    "e84393",
    "00b894",
    "eb3b5a",
    "2d98da",
    "0fb9b1",
    "34ace0",
    "33d9b2",
    "ff793f",
    "ff3f34",
    "0fbcf9",
    "f53b57",
    "3c40c6",
    "c44569",
    "f19066",
    "303952",
    "60a3bc",
    "b71540",
    "FDA7DF",
    "A3CB38",
    "78e08f",
    "22a6b3",
    "be2edd",
    "4834d4",
    "130f40",
    "eb4d4b",
    "6ab04c",
    "c23616",
    "0097e6",
    "8c7ae6",
    "e1b12c",
    "44bd32",
    "40739e",
    "f368e0",
    "ff9f43",
    "ee5253",
    "0abde3",
    "10ac84",
    "01a3a4",
    "2e86de",
    "341f97",
    "fa8231",
    "20bf6b",
    "8854d0",
    "4b6584",
    "ccae62",
    "cd6133",
    "b33939",
    "05c46b",
    "00d8d6",
    "8e44ad",
  ];

  static const String iconPath = "assets/icons/";
  static const List<String> icons = [
    "accessories",
    "add_balance",
    "add_transaction",
    "app_lock",
    "balance_transfer",
    "withdraw_balance",
    "bank",
    "bills",
    "bonuses",
    "budgets",
    "cafes",
    "calendar",
    "cash",
    "cash_withdrawal",
    "categories",
    "charity",
    "children",
    "clothing",
    "credit_card",
    "crossed_eye",
    "currency",
    "debts",
    "default_icon_picked",
    "delete",
    "doctors",
    "donations_and_gifts",
    "e_wallet",
    "edit",
    "education",
    "electricity",
    "entertainment",
    "expense",
    "expenses_gifts",
    "expenses_other",
    "eye",
    "family",
    "fees_and_subscriptions",
    "food",
    "games",
    "garage",
    "gas",
    "gasoline",
    "gifts",
    "health_and_fitness",
    "home",
    "home_maintenance",
    "income",
    "income_other",
    "insurance",
    "internet",
    "investment",
    "language",
    "lock",
    "maintenance",
    "medicines",
    "menu",
    "mobile_screenshot",
    "movies_and_audio",
    "overtime",
    "paying_debts_and_installments",
    "personal_care",
    "pets",
    "picker_color",
    "receiving_debts_and_installments",
    "rent",
    "report",
    "restaurants",
    "salary",
    "sales",
    "search_currency",
    "services",
    "settings",
    "share",
    "shoes",
    "shopping",
    "sports",
    "tags",
    "taxis",
    "telecommunications",
    "textbooks",
    "theme_mode",
    "training_courses",
    "transaction",
    "transportation",
    "travel",
    "tv",
    "unlock",
    "wallet_investment",
    "wallet_type_other",
    "wallets",
    "water",
    "zakat",
  ];

  static const List<String> calculatorButtons = [
    'C',
    'DEL',
    '%',
    '/',
    '7',
    '8',
    '9',
    '*',
    '4',
    '5',
    '6',
    '-',
    '1',
    '2',
    '3',
    '+',
    '',
    '0',
    '.',
    '=',
  ];
}
